blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Idea
    url: https://github.com/Mrxx99/Playnite.GameJoltLibrary/discussions/new?category=ideas
    about: Have an idea, create it here.
  - name: ğŸ—¨ Discussions
    url: https://github.com/Tyrrrz/YoutubeDownloader/discussions/new
    about: Ask and answer questions.
